# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('rating', models.FloatField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
